apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "optictrace.fullname" . }}
  labels: {{- include "optictrace.labels" . | nindent 4 }}
data:
  optic.yaml: |
{{ toYaml .Values.config | indent 4 }}
