apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "optictrace.fullname" . }}
  labels: {{- include "optictrace.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: optictrace
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels: {{- include "optictrace.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ toYaml .Values.config | sha256sum }}
    spec:
      containers:
        - name: optictrace
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - run
            - -config
            - /etc/optictrace/optic.yaml
            - -ui
            - /usr/share/optictrace/ui
          ports:
            - name: proxy
              containerPort: {{ .Values.service.proxyPort }}
            - name: admin
              containerPort: {{ .Values.service.adminPort }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: admin
          readinessProbe:
            httpGet:
              path: /healthz
              port: admin
          resources: {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/optictrace
              readOnly: true
            - name: data
              mountPath: /data
      volumes:
        - name: config
          configMap:
            name: {{ include "optictrace.fullname" . }}
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "optictrace.fullname" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
