{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "optictrace.fullname" . }}
  labels: {{- include "optictrace.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: optictrace
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: admin
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
