apiVersion: v1
kind: Service
metadata:
  name: {{ include "optictrace.fullname" . }}
  labels: {{- include "optictrace.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: optictrace
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: proxy
      port: {{ .Values.service.proxyPort }}
      targetPort: proxy
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
