#!/usr/bin/env bash
# Regenerate the Homebrew formula for a released version and push it to the tap.
#
# Why a formula and not a cask: casks are macOS-only, and OpticTrace ships
# Linux binaries too — one formula serves both. Casks of unsigned binaries
# also trip macOS Gatekeeper quarantine, which a formula avoids entirely.
#
# Hashes come from the release's own checksums.txt rather than a local build,
# so what the formula claims and what a user downloads cannot drift apart.
#
#   ./scripts/update-tap.sh v0.7.0
set -euo pipefail

VERSION="${1:?usage: update-tap.sh vX.Y.Z}"
VER="${VERSION#v}"
OWNER="dwarka-prasad"
REPO="optictrace"
TAP="homebrew-tap"
BASE="https://github.com/${OWNER}/${REPO}/releases/download/${VERSION}"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

echo "Fetching published checksums for ${VERSION}…"
curl -fsSL -o "$work/checksums.txt" "${BASE}/checksums.txt"

sha() {
  local name="$1"
  local h
  h="$(grep -E "  ${name}\$" "$work/checksums.txt" | awk '{print $1}')"
  [ -n "$h" ] || { echo "no checksum for $name" >&2; exit 1; }
  echo "$h"
}

DA="$(sha "optictrace_${VER}_darwin_amd64.tar.gz")"
DR="$(sha "optictrace_${VER}_darwin_arm64.tar.gz")"
LA="$(sha "optictrace_${VER}_linux_amd64.tar.gz")"
LR="$(sha "optictrace_${VER}_linux_arm64.tar.gz")"

cat > "$work/optictrace.rb" <<EOF
# Generated by scripts/update-tap.sh — do not edit by hand.
class Optictrace < Formula
  desc "Declarative API telemetry and governance gateway"
  homepage "https://dwarka-prasad.github.io/optictrace/"
  license "Apache-2.0"
  # No \`version\` stanza: Homebrew derives it from the URL, and declaring
  # it as well is flagged by \`brew audit\` as redundant.

  on_macos do
    on_intel do
      url "${BASE}/optictrace_${VER}_darwin_amd64.tar.gz"
      sha256 "${DA}"
    end
    on_arm do
      url "${BASE}/optictrace_${VER}_darwin_arm64.tar.gz"
      sha256 "${DR}"
    end
  end

  on_linux do
    on_intel do
      url "${BASE}/optictrace_${VER}_linux_amd64.tar.gz"
      sha256 "${LA}"
    end
    on_arm do
      url "${BASE}/optictrace_${VER}_linux_arm64.tar.gz"
      sha256 "${LR}"
    end
  end

  def install
    bin.install "optictrace"
    # The release archive ships an annotated example config and its rule
    # tests; keeping them means \`brew install\` leaves you with something
    # runnable rather than just a binary.
    pkgshare.install "optic.yaml", "optic.test.yaml"
  end

  def caveats
    <<~EOS
      An example configuration is installed at:
        #{opt_pkgshare}/optic.yaml

      Get started:
        optictrace validate -config #{opt_pkgshare}/optic.yaml
        optictrace run      -config optic.yaml
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/optictrace version")
    # Prove the binary actually works, not just that it runs: validate the
    # shipped config and run its governance assertions.
    system bin/"optictrace", "validate", "-config", pkgshare/"optic.yaml"
    system bin/"optictrace", "test",
           "-config", pkgshare/"optic.yaml",
           "-tests", pkgshare/"optic.test.yaml"
  end
end
EOF

echo "Cloning tap…"
git clone --depth=1 "https://github.com/${OWNER}/${TAP}.git" "$work/tap" 2>/dev/null \
  || { mkdir -p "$work/tap" && git -C "$work/tap" init -q \
       && git -C "$work/tap" remote add origin "https://github.com/${OWNER}/${TAP}.git"; }

mkdir -p "$work/tap/Formula"
cp "$work/optictrace.rb" "$work/tap/Formula/optictrace.rb"

cd "$work/tap"
git add Formula/optictrace.rb
if git diff --cached --quiet; then
  echo "Formula already up to date."
  exit 0
fi
git commit -q -m "optictrace ${VERSION}"
git push -q origin HEAD:main
echo "✓ Pushed optictrace ${VERSION} to ${OWNER}/${TAP}"
