package spec

import (
	"fmt"
	"strings"
)

// GenerateGo emits a typed Go client: structs for request/response bodies and
// one method per operation, using only net/http and encoding/json.
func GenerateGo(s *Spec, pkgName string) string {
	if pkgName == "" {
		pkgName = "apiclient"
	}
	var types strings.Builder
	var methods strings.Builder
	emitted := map[string]bool{}

	for _, path := range sortedKeys(s.Paths) {
		for _, method := range sortedKeys(s.Paths[path]) {
			op := s.Paths[path][method]
			opID := op.OperationID
			if opID == "" {
				opID = operationID(method, path)
			}
			fnName := exportName(opID)

			reqType := ""
			if sc := s.requestSchema(op); sc != nil {
				reqType = fnName + "Request"
				emitGoStruct(&types, s, reqType, sc, emitted)
			}
			respType := ""
			if sc := s.responseSchema(op, ""); sc != nil {
				respType = fnName + "Response"
				emitGoStruct(&types, s, respType, sc, emitted)
			}

			args := []string{"ctx context.Context"}
			for _, p := range pathParams(path) {
				args = append(args, goIdent(p)+" string")
			}
			var queryArgs []string
			for _, p := range op.Parameters {
				if p.In == "query" {
					args = append(args, goIdent(p.Name)+" string")
					queryArgs = append(queryArgs, p.Name)
				}
			}
			if reqType != "" {
				args = append(args, "body "+reqType)
			}

			retType := "error"
			if respType != "" {
				retType = "(*" + respType + ", error)"
			}

			fmt.Fprintf(&methods, "\n// %s calls %s %s.\n", fnName, strings.ToUpper(method), path)
			fmt.Fprintf(&methods, "func (c *Client) %s(%s) %s {\n", fnName, strings.Join(args, ", "), retType)
			fmt.Fprintf(&methods, "\tpath := %s\n", goPathExpr(path))
			if len(queryArgs) > 0 {
				fmt.Fprintf(&methods, "\tq := url.Values{}\n")
				for _, qa := range queryArgs {
					fmt.Fprintf(&methods, "\tif %s != \"\" {\n\t\tq.Set(%q, %s)\n\t}\n", goIdent(qa), qa, goIdent(qa))
				}
				fmt.Fprintf(&methods, "\tif len(q) > 0 {\n\t\tpath += \"?\" + q.Encode()\n\t}\n")
			}
			bodyArg := "nil"
			if reqType != "" {
				bodyArg = "body"
			}
			if respType != "" {
				fmt.Fprintf(&methods, "\tvar out %s\n", respType)
				fmt.Fprintf(&methods, "\tif err := c.do(ctx, %q, path, %s, &out); err != nil {\n\t\treturn nil, err\n\t}\n",
					strings.ToUpper(method), bodyArg)
				fmt.Fprintf(&methods, "\treturn &out, nil\n}\n")
			} else {
				fmt.Fprintf(&methods, "\treturn c.do(ctx, %q, path, %s, nil)\n}\n",
					strings.ToUpper(method), bodyArg)
			}
		}
	}

	return fmt.Sprintf(`// Code generated by "optictrace sdk -lang go" — DO NOT EDIT.
// Source: %s (%s)

package %s

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// APIError is returned for any non-2xx response.
type APIError struct {
	Status int
	Body   []byte
}

func (e *APIError) Error() string {
	return fmt.Sprintf("api error %%d: %%s", e.Status, string(e.Body))
}

// Client is a typed client for %s.
type Client struct {
	BaseURL string
	Headers map[string]string
	HTTP    *http.Client
}

// NewClient returns a Client with sensible defaults.
func NewClient(baseURL string) *Client {
	return &Client{
		BaseURL: strings.TrimRight(baseURL, "/"),
		Headers: map[string]string{},
		HTTP:    &http.Client{Timeout: 30 * time.Second},
	}
}

func (c *Client) do(ctx context.Context, method, path string, body, out any) error {
	var reader io.Reader
	if body != nil {
		raw, err := json.Marshal(body)
		if err != nil {
			return err
		}
		reader = bytes.NewReader(raw)
	}
	req, err := http.NewRequestWithContext(ctx, method, c.BaseURL+path, reader)
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")
	for k, v := range c.Headers {
		req.Header.Set(k, v)
	}
	httpClient := c.HTTP
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	resp, err := httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return err
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return &APIError{Status: resp.StatusCode, Body: raw}
	}
	if out != nil && len(raw) > 0 {
		return json.Unmarshal(raw, out)
	}
	return nil
}

%s%s`, s.Info.Title, s.Info.Version, pkgName, s.Info.Title, types.String(), methods.String())
}

func emitGoStruct(out *strings.Builder, s *Spec, name string, sc *Schema, emitted map[string]bool) {
	if emitted[name] {
		return
	}
	emitted[name] = true
	sc = s.Resolve(sc)
	if sc == nil || sc.Type != "object" || len(sc.Properties) == 0 {
		fmt.Fprintf(out, "type %s = %s\n\n", name, goType(s, sc, 0))
		return
	}
	required := map[string]bool{}
	for _, r := range sc.Required {
		required[r] = true
	}
	fmt.Fprintf(out, "type %s struct {\n", name)
	for _, k := range sortedKeys(sc.Properties) {
		tag := k
		if !required[k] {
			tag += ",omitempty"
		}
		fmt.Fprintf(out, "\t%s %s `json:%q`\n", exportName(k), goType(s, sc.Properties[k], 1), tag)
	}
	fmt.Fprintf(out, "}\n\n")
}

func goType(s *Spec, sc *Schema, depth int) string {
	sc = s.Resolve(sc)
	if sc == nil || depth > 8 {
		return "any"
	}
	switch sc.Type {
	case "string":
		return "string"
	case "integer":
		return "int64"
	case "number":
		return "float64"
	case "boolean":
		return "bool"
	case "array":
		return "[]" + goType(s, sc.Items, depth+1)
	case "object":
		if len(sc.Properties) == 0 {
			return "map[string]any"
		}
		// Inline anonymous struct keeps the generated client self-contained
		// without inventing names for every nested object.
		var b strings.Builder
		b.WriteString("struct {\n")
		required := map[string]bool{}
		for _, r := range sc.Required {
			required[r] = true
		}
		indent := strings.Repeat("\t", depth+1)
		for _, k := range sortedKeys(sc.Properties) {
			tag := k
			if !required[k] {
				tag += ",omitempty"
			}
			fmt.Fprintf(&b, "%s\t%s %s `json:%q`\n", indent, exportName(k), goType(s, sc.Properties[k], depth+1), tag)
		}
		fmt.Fprintf(&b, "%s}", indent)
		return b.String()
	default:
		return "any"
	}
}

// goPathExpr builds either a literal or an fmt.Sprintf for templated paths.
func goPathExpr(path string) string {
	params := pathParams(path)
	if len(params) == 0 {
		return fmt.Sprintf("%q", path)
	}
	format := path
	args := make([]string, 0, len(params))
	for _, p := range params {
		format = strings.ReplaceAll(format, "{"+p+"}", "%s")
		args = append(args, goIdent(p))
	}
	return fmt.Sprintf("fmt.Sprintf(%q, %s)", format, strings.Join(args, ", "))
}

var goKeywords = map[string]bool{
	"type": true, "func": true, "range": true, "map": true, "chan": true, "select": true,
	"go": true, "defer": true, "package": true, "import": true, "var": true, "const": true,
	"return": true, "if": true, "else": true, "for": true, "switch": true, "case": true,
	"interface": true, "struct": true, "len": true, "cap": true, "ctx": true, "body": true,
}

// goIdent produces a lowerCamelCase parameter name safe from collisions.
func goIdent(s string) string {
	name := exportName(s)
	if name == "" {
		return "param"
	}
	name = strings.ToLower(name[:1]) + name[1:]
	if goKeywords[name] {
		name += "Param"
	}
	return name
}
