package spec

import (
	"encoding/json"
	"fmt"
	"math"
	"sort"
	"strconv"
	"strings"

	"github.com/dwarka-prasad/optictrace/internal/engine"
	"github.com/dwarka-prasad/optictrace/internal/store"
)

// Infer learns an OpenAPI document from captured traffic. Payload shapes are
// merged across every observed exchange, so the result reflects what clients
// ACTUALLY send — including the edge cases nobody documented. Values that
// arrive redacted ("[REDACTED]") still contribute their field name and a
// string type, so governance never hides API *structure*, only data.
func Infer(serviceName string, records []store.Record) *Spec {
	type opAgg struct {
		count        int64
		reqSchema    *Schema
		respByStatus map[string]*Schema
	}
	ops := map[string]map[string]*opAgg{} // path -> METHOD -> agg

	for i := range records {
		rec := &records[i]
		path := openAPIPath(rec.Path)
		method := strings.ToLower(rec.Method)
		if ops[path] == nil {
			ops[path] = map[string]*opAgg{}
		}
		agg := ops[path][method]
		if agg == nil {
			agg = &opAgg{respByStatus: map[string]*Schema{}}
			ops[path][method] = agg
		}
		agg.count++

		if sc := schemaOfJSON(rec.RequestBody); sc != nil {
			agg.reqSchema = mergeSchemas(agg.reqSchema, sc)
		}
		if sc := schemaOfJSON(rec.ResponseBody); sc != nil {
			status := strconv.Itoa(rec.Status)
			agg.respByStatus[status] = mergeSchemas(agg.respByStatus[status], sc)
		} else if rec.Status != 0 {
			status := strconv.Itoa(rec.Status)
			if _, ok := agg.respByStatus[status]; !ok {
				agg.respByStatus[status] = nil // status observed, body unknown/restricted
			}
		}
	}

	title := serviceName
	if title == "" {
		title = "API"
	}
	out := &Spec{
		OpenAPI: "3.0.3",
		Info: Info{
			Title:       title,
			Version:     "traffic-inferred",
			Description: "Generated by OpticTrace from observed traffic. Bodies reflect governed telemetry: restricted routes contribute status codes only; redacted fields appear as strings.",
		},
		Paths: map[string]map[string]*Operation{},
	}

	for path, methods := range ops {
		out.Paths[path] = map[string]*Operation{}
		for method, agg := range methods {
			op := &Operation{
				Summary:     fmt.Sprintf("Observed %d time(s)", agg.count),
				OperationID: operationID(method, path),
				Responses:   map[string]*Response{},
			}
			for _, p := range pathParams(path) {
				op.Parameters = append(op.Parameters, &Param{
					Name: p, In: "path", Required: true, Schema: &Schema{Type: "string"},
				})
			}
			if agg.reqSchema != nil {
				op.RequestBody = &RequestBody{
					Required: true,
					Content:  map[string]*Media{"application/json": {Schema: agg.reqSchema}},
				}
			}
			statuses := make([]string, 0, len(agg.respByStatus))
			for s := range agg.respByStatus {
				statuses = append(statuses, s)
			}
			sort.Strings(statuses)
			for _, status := range statuses {
				resp := &Response{Description: "Observed response"}
				if sc := agg.respByStatus[status]; sc != nil {
					resp.Content = map[string]*Media{"application/json": {Schema: sc}}
				}
				op.Responses[status] = resp
			}
			if len(op.Responses) == 0 {
				op.Responses["default"] = &Response{Description: "Observed response"}
			}
			out.Paths[path][method] = op
		}
	}
	return out
}

// openAPIPath converts a concrete request path into an OpenAPI template,
// reusing the engine's identifier heuristics: /users/42 -> /users/{id}.
func openAPIPath(p string) string {
	norm := engine.NormalizeRoute(p)
	segs := splitSegs(norm)
	n := 0
	for i, s := range segs {
		if s == ":id" {
			name := "id"
			if n > 0 {
				name = fmt.Sprintf("id%d", n+1)
			}
			// Prefer a resource-derived name: /users/{userId}.
			if i > 0 {
				name = paramNameFor(segs[i-1], n)
			}
			segs[i] = "{" + name + "}"
			n++
		}
	}
	return "/" + strings.Join(segs, "/")
}

func paramNameFor(resource string, ordinal int) string {
	r := strings.TrimSuffix(resource, "s")
	r = strings.Map(func(c rune) rune {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') {
			return c
		}
		return -1
	}, r)
	if r == "" {
		if ordinal > 0 {
			return fmt.Sprintf("id%d", ordinal+1)
		}
		return "id"
	}
	return r + "Id"
}

func pathParams(tmpl string) []string {
	var out []string
	for _, s := range splitSegs(tmpl) {
		if strings.HasPrefix(s, "{") && strings.HasSuffix(s, "}") {
			out = append(out, strings.Trim(s, "{}"))
		}
	}
	return out
}

func operationID(method, path string) string {
	var b strings.Builder
	b.WriteString(method)
	for _, seg := range splitSegs(path) {
		if strings.HasPrefix(seg, "{") {
			b.WriteString("By" + exportName(strings.Trim(seg, "{}")))
			continue
		}
		b.WriteString(exportName(seg))
	}
	return b.String()
}

func exportName(s string) string {
	parts := strings.FieldsFunc(s, func(c rune) bool {
		return !((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9'))
	})
	var b strings.Builder
	for _, p := range parts {
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}

// schemaOfJSON infers a schema from one captured JSON body ("" or non-JSON
// returns nil).
func schemaOfJSON(body string) *Schema {
	if body == "" || (body[0] != '{' && body[0] != '[') {
		return nil
	}
	var v any
	if err := json.Unmarshal([]byte(body), &v); err != nil {
		return nil
	}
	return schemaOfValue(v, 0)
}

func schemaOfValue(v any, depth int) *Schema {
	if depth > 12 {
		return &Schema{}
	}
	switch t := v.(type) {
	case map[string]any:
		sc := &Schema{Type: "object", Properties: map[string]*Schema{}}
		for k, child := range t {
			sc.Properties[k] = schemaOfValue(child, depth+1)
			sc.Required = append(sc.Required, k)
		}
		sort.Strings(sc.Required)
		return sc
	case []any:
		sc := &Schema{Type: "array"}
		for _, item := range t {
			sc.Items = mergeSchemas(sc.Items, schemaOfValue(item, depth+1))
		}
		if sc.Items == nil {
			sc.Items = &Schema{}
		}
		return sc
	case string:
		sc := &Schema{Type: "string"}
		if t != "" && t != "[REDACTED]" {
			sc.Example = t
		}
		return sc
	case float64:
		if t == math.Trunc(t) && math.Abs(t) < 1e15 {
			return &Schema{Type: "integer", Example: int64(t)}
		}
		return &Schema{Type: "number", Example: t}
	case bool:
		return &Schema{Type: "boolean"}
	case nil:
		return &Schema{Nullable: true}
	default:
		return &Schema{}
	}
}

// mergeSchemas unions two observed shapes: properties accumulate, required
// keeps only fields present in EVERY observation, conflicting scalar types
// widen (integer+number -> number, otherwise untyped "any").
func mergeSchemas(a, b *Schema) *Schema {
	if a == nil {
		return b
	}
	if b == nil {
		return a
	}
	out := &Schema{}

	switch {
	case a.Type == b.Type:
		out.Type = a.Type
	case a.Type == "": // untyped side (e.g. observed null) adopts the other
		out.Type = b.Type
	case b.Type == "":
		out.Type = a.Type
	case (a.Type == "integer" && b.Type == "number") || (a.Type == "number" && b.Type == "integer"):
		out.Type = "number"
	default:
		out.Type = "" // genuinely mixed -> any
	}
	out.Nullable = a.Nullable || b.Nullable
	if out.Example = a.Example; out.Example == nil {
		out.Example = b.Example
	}

	if a.Properties != nil || b.Properties != nil {
		out.Properties = map[string]*Schema{}
		for k, v := range a.Properties {
			out.Properties[k] = v
		}
		for k, v := range b.Properties {
			out.Properties[k] = mergeSchemas(out.Properties[k], v)
		}
		// required = intersection of presence across observations
		req := map[string]bool{}
		for _, k := range a.Required {
			req[k] = true
		}
		out.Required = nil
		for _, k := range b.Required {
			if req[k] {
				out.Required = append(out.Required, k)
			}
		}
		sort.Strings(out.Required)
	}
	if a.Items != nil || b.Items != nil {
		out.Items = mergeSchemas(a.Items, b.Items)
	}
	return out
}
