package spec

import (
	"fmt"
	"sort"
	"strings"
)

// GeneratePython emits a typed Python client: TypedDict models plus one
// method per operation. Standard library only (urllib) so a generated client
// has no dependency footprint — the same posture as the TypeScript emitter,
// which uses fetch rather than a HTTP library.
func GeneratePython(s *Spec) string {
	var models strings.Builder
	var methods strings.Builder
	emitted := map[string]bool{}

	paths := sortedKeys(s.Paths)
	for _, path := range paths {
		for _, method := range sortedKeys(s.Paths[path]) {
			op := s.Paths[path][method]
			opID := op.OperationID
			if opID == "" {
				opID = operationID(method, path)
			}
			fnName := snake(opID)

			reqType := ""
			if sc := s.requestSchema(op); sc != nil {
				reqType = exportName(opID) + "Request"
				emitTypedDict(&models, s, reqType, sc, emitted)
			}
			respType := "Any"
			if sc := s.responseSchema(op, ""); sc != nil {
				respType = exportName(opID) + "Response"
				emitTypedDict(&models, s, respType, sc, emitted)
			}

			args := []string{"self"}
			for _, p := range pathParams(path) {
				args = append(args, fmt.Sprintf("%s: str", snake(p)))
			}
			for _, p := range op.Parameters {
				if p.In == "query" {
					opt := " | None = None"
					if p.Required {
						opt = ""
					}
					args = append(args, fmt.Sprintf("%s: str%s", snake(p.Name), opt))
				}
			}
			hasBody := reqType != ""
			if hasBody {
				args = append(args, "body: "+reqType)
			}

			fmt.Fprintf(&methods, "\n    def %s(%s) -> %s:\n", fnName, strings.Join(args, ", "), respType)
			fmt.Fprintf(&methods, "        \"\"\"%s %s\"\"\"\n", strings.ToUpper(method), path)
			fmt.Fprintf(&methods, "        path = f%q\n", pythonPath(path))

			var queryParams []string
			for _, p := range op.Parameters {
				if p.In == "query" {
					queryParams = append(queryParams, fmt.Sprintf("%q: %s", p.Name, snake(p.Name)))
				}
			}
			if len(queryParams) > 0 {
				fmt.Fprintf(&methods, "        params = {%s}\n", strings.Join(queryParams, ", "))
				fmt.Fprintf(&methods, "        params = {k: v for k, v in params.items() if v is not None}\n")
			} else {
				fmt.Fprintf(&methods, "        params = None\n")
			}
			bodyArg := "None"
			if hasBody {
				bodyArg = "body"
			}
			fmt.Fprintf(&methods, "        return self._request(%q, path, %s, params)  # type: ignore[return-value]\n",
				strings.ToUpper(method), bodyArg)
		}
	}

	className := exportName(sanitizeTitle(s.Info.Title)) + "Client"
	return fmt.Sprintf(`"""Code generated by "optictrace sdk -lang python" — DO NOT EDIT.

Source: %s (%s)
Standard library only: no runtime dependencies.
"""

from __future__ import annotations

import json
import urllib.error
import urllib.parse
import urllib.request
from typing import Any, TypedDict

__all__ = ["%s", "ApiError"]


class ApiError(Exception):
    """Raised for any non-2xx response."""

    def __init__(self, status: int, body: Any) -> None:
        super().__init__(f"API error {status}")
        self.status = status
        self.body = body


%s
class %s:
    def __init__(
        self,
        base_url: str,
        headers: dict[str, str] | None = None,
        timeout: float = 30.0,
    ) -> None:
        self.base_url = base_url.rstrip("/")
        self.headers = headers or {}
        self.timeout = timeout

    def _request(
        self,
        method: str,
        path: str,
        body: Any = None,
        params: dict[str, Any] | None = None,
    ) -> Any:
        url = self.base_url + path
        if params:
            url += "?" + urllib.parse.urlencode(params)
        data = json.dumps(body).encode() if body is not None else None
        req = urllib.request.Request(
            url,
            data=data,
            method=method,
            headers={"Content-Type": "application/json", **self.headers},
        )
        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                raw = resp.read()
                return json.loads(raw) if raw else None
        except urllib.error.HTTPError as exc:
            raw = exc.read()
            parsed = json.loads(raw) if raw else None
            raise ApiError(exc.code, parsed) from exc
%s`, s.Info.Title, s.Info.Version, className, models.String(), className, methods.String())
}

func emitTypedDict(out *strings.Builder, s *Spec, name string, sc *Schema, emitted map[string]bool) {
	if emitted[name] {
		return
	}
	emitted[name] = true
	sc = s.Resolve(sc)
	if sc == nil || sc.Type != "object" || len(sc.Properties) == 0 {
		fmt.Fprintf(out, "%s = %s\n\n", name, pyType(s, sc, 0))
		return
	}
	required := map[string]bool{}
	for _, r := range sc.Required {
		required[r] = true
	}
	// total=False lets optional keys be omitted; required ones are declared
	// in a base class so the type checker still enforces them.
	var req, opt []string
	for _, k := range sortedKeys(sc.Properties) {
		line := fmt.Sprintf("    %s: %s", pyIdent(k), pyType(s, sc.Properties[k], 1))
		if required[k] {
			req = append(req, line)
		} else {
			opt = append(opt, line)
		}
	}
	if len(req) > 0 {
		fmt.Fprintf(out, "class %sRequired(TypedDict):\n%s\n\n", name, strings.Join(req, "\n"))
		fmt.Fprintf(out, "class %s(%sRequired, total=False):\n", name, name)
		if len(opt) == 0 {
			fmt.Fprintf(out, "    pass\n\n")
		} else {
			fmt.Fprintf(out, "%s\n\n", strings.Join(opt, "\n"))
		}
		return
	}
	fmt.Fprintf(out, "class %s(TypedDict, total=False):\n", name)
	if len(opt) == 0 {
		fmt.Fprintf(out, "    pass\n\n")
	} else {
		fmt.Fprintf(out, "%s\n\n", strings.Join(opt, "\n"))
	}
}

func pyType(s *Spec, sc *Schema, depth int) string {
	sc = s.Resolve(sc)
	if sc == nil || depth > 8 {
		return "Any"
	}
	base := "Any"
	switch sc.Type {
	case "string":
		base = "str"
	case "integer":
		base = "int"
	case "number":
		base = "float"
	case "boolean":
		base = "bool"
	case "array":
		base = "list[" + pyType(s, sc.Items, depth+1) + "]"
	case "object":
		base = "dict[str, Any]"
	}
	if sc.Nullable && base != "Any" {
		return base + " | None"
	}
	return base
}

// pythonPath turns /users/{userId} into an f-string body: /users/{user_id}
func pythonPath(path string) string {
	out := path
	for _, p := range pathParams(path) {
		out = strings.ReplaceAll(out, "{"+p+"}", "{"+snake(p)+"}")
	}
	return out
}

var pyKeywords = map[string]bool{
	"class": true, "def": true, "from": true, "import": true, "return": true,
	"lambda": true, "global": true, "pass": true, "None": true, "True": true, "False": true,
	"and": true, "or": true, "not": true, "in": true, "is": true, "if": true, "else": true,
}

func pyIdent(s string) string {
	out := snake(s)
	if out == "" || pyKeywords[out] {
		out += "_"
	}
	return out
}

// snake converts CamelCase / kebab-case / dotted names to snake_case.
func snake(s string) string {
	var b strings.Builder
	prevLower := false
	for i, r := range s {
		switch {
		case r >= 'A' && r <= 'Z':
			if prevLower && i > 0 {
				b.WriteByte('_')
			}
			b.WriteRune(r - 'A' + 'a')
			prevLower = false
		case (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9'):
			b.WriteRune(r)
			prevLower = true
		default:
			b.WriteByte('_')
			prevLower = false
		}
	}
	out := strings.Trim(b.String(), "_")
	for strings.Contains(out, "__") {
		out = strings.ReplaceAll(out, "__", "_")
	}
	if out == "" || (out[0] >= '0' && out[0] <= '9') {
		out = "p" + out
	}
	return out
}

func sortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
