package spec

import (
	"fmt"
	"sort"
	"strings"
)

// GenerateTypeScript emits a self-contained, dependency-free typed client
// (fetch-based) from a spec. Interfaces are derived from request/response
// schemas; one async method per operation.
//
// This is the first generator target; the traversal is generator-agnostic,
// so Python/Go emitters can reuse the same walk (roadmap).
func GenerateTypeScript(s *Spec) string {
	var types strings.Builder
	var methods strings.Builder
	emitted := map[string]bool{}

	paths := make([]string, 0, len(s.Paths))
	for p := range s.Paths {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	for _, path := range paths {
		methodsOfPath := make([]string, 0, len(s.Paths[path]))
		for m := range s.Paths[path] {
			methodsOfPath = append(methodsOfPath, m)
		}
		sort.Strings(methodsOfPath)

		for _, method := range methodsOfPath {
			op := s.Paths[path][method]
			opID := op.OperationID
			if opID == "" {
				opID = operationID(method, path)
			}
			fnName := lowerFirst(opID)

			// --- named types for request/response ------------------------
			reqType := "void"
			if sc := s.requestSchema(op); sc != nil {
				reqType = exportName(opID) + "Request"
				emitInterface(&types, s, reqType, sc, emitted)
			}
			respType := "unknown"
			if sc := s.responseSchema(op, ""); sc != nil {
				respType = exportName(opID) + "Response"
				emitInterface(&types, s, respType, sc, emitted)
			}

			// --- client method --------------------------------------------
			params := pathParams(path)
			var args []string
			for _, p := range params {
				args = append(args, fmt.Sprintf("%s: string | number", tsIdent(p)))
			}
			hasBody := reqType != "void"
			if hasBody {
				args = append(args, "body: "+reqType)
			}
			urlExpr := "`" + templateToTS(path) + "`"

			fmt.Fprintf(&methods, "\n  /** %s %s */\n", strings.ToUpper(method), path)
			fmt.Fprintf(&methods, "  async %s(%s): Promise<%s> {\n", fnName, strings.Join(args, ", "), respType)
			fmt.Fprintf(&methods, "    return this.request(%q, %s%s);\n",
				strings.ToUpper(method), urlExpr, map[bool]string{true: ", body", false: ""}[hasBody])
			fmt.Fprintf(&methods, "  }\n")
		}
	}

	return fmt.Sprintf(`// Code generated by "optictrace sdk -lang typescript" — DO NOT EDIT.
// Source: %s (%s)
/* eslint-disable */

%s
export interface ClientOptions {
  baseUrl: string;
  headers?: Record<string, string>;
  fetch?: typeof fetch;
}

export class ApiError extends Error {
  constructor(
    public status: number,
    public body: unknown,
  ) {
    super("API error " + status);
  }
}

export class %sClient {
  private baseUrl: string;
  private headers: Record<string, string>;
  private fetchImpl: typeof fetch;

  constructor(options: ClientOptions) {
    this.baseUrl = options.baseUrl.replace(/\/+$/, "");
    this.headers = options.headers ?? {};
    this.fetchImpl = options.fetch ?? fetch;
  }

  private async request<T>(method: string, path: string, body?: unknown): Promise<T> {
    const res = await this.fetchImpl(this.baseUrl + path, {
      method,
      headers: { "Content-Type": "application/json", ...this.headers },
      body: body === undefined ? undefined : JSON.stringify(body),
    });
    const text = await res.text();
    const data = text ? JSON.parse(text) : undefined;
    if (!res.ok) throw new ApiError(res.status, data);
    return data as T;
  }
%s}
`, s.Info.Title, s.Info.Version, types.String(), exportName(sanitizeTitle(s.Info.Title)), methods.String())
}

func emitInterface(out *strings.Builder, s *Spec, name string, sc *Schema, emitted map[string]bool) {
	if emitted[name] {
		return
	}
	emitted[name] = true
	sc = s.Resolve(sc)
	if sc == nil || sc.Type != "object" || len(sc.Properties) == 0 {
		fmt.Fprintf(out, "export type %s = %s;\n\n", name, tsType(s, sc, 0))
		return
	}
	required := map[string]bool{}
	for _, r := range sc.Required {
		required[r] = true
	}
	keys := make([]string, 0, len(sc.Properties))
	for k := range sc.Properties {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	fmt.Fprintf(out, "export interface %s {\n", name)
	for _, k := range keys {
		opt := "?"
		if required[k] {
			opt = ""
		}
		fmt.Fprintf(out, "  %s%s: %s;\n", tsProp(k), opt, tsType(s, sc.Properties[k], 1))
	}
	fmt.Fprintf(out, "}\n\n")
}

func tsType(s *Spec, sc *Schema, depth int) string {
	sc = s.Resolve(sc)
	if sc == nil || depth > 8 {
		return "unknown"
	}
	base := func() string {
		switch sc.Type {
		case "string":
			if len(sc.Enum) > 0 {
				var parts []string
				for _, e := range sc.Enum {
					parts = append(parts, fmt.Sprintf("%q", fmt.Sprint(e)))
				}
				return strings.Join(parts, " | ")
			}
			return "string"
		case "integer", "number":
			return "number"
		case "boolean":
			return "boolean"
		case "array":
			return "Array<" + tsType(s, sc.Items, depth+1) + ">"
		case "object":
			if len(sc.Properties) == 0 {
				return "Record<string, unknown>"
			}
			keys := make([]string, 0, len(sc.Properties))
			for k := range sc.Properties {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			required := map[string]bool{}
			for _, r := range sc.Required {
				required[r] = true
			}
			var b strings.Builder
			b.WriteString("{ ")
			for i, k := range keys {
				if i > 0 {
					b.WriteString("; ")
				}
				opt := "?"
				if required[k] {
					opt = ""
				}
				b.WriteString(tsProp(k) + opt + ": " + tsType(s, sc.Properties[k], depth+1))
			}
			b.WriteString(" }")
			return b.String()
		default:
			return "unknown"
		}
	}()
	if sc.Nullable {
		return base + " | null"
	}
	return base
}

var tsIdentRe = strings.NewReplacer("-", "_", ".", "_", " ", "_")

func tsIdent(s string) string {
	out := tsIdentRe.Replace(s)
	if out == "" || (out[0] >= '0' && out[0] <= '9') {
		out = "p" + out
	}
	return out
}

func tsProp(s string) string {
	for _, c := range s {
		if !((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' || c == '$') {
			return fmt.Sprintf("%q", s)
		}
	}
	if s == "" {
		return `""`
	}
	return s
}

// templateToTS converts /users/{userId} into `/users/${userId}` innards.
func templateToTS(path string) string {
	out := path
	for _, p := range pathParams(path) {
		out = strings.ReplaceAll(out, "{"+p+"}", "${"+tsIdent(p)+"}")
	}
	return out
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func sanitizeTitle(s string) string {
	if s == "" {
		return "Api"
	}
	return s
}
